### 🔹 Crear un follow
POST http://localhost:4200/api/user-follows
Content-Type: application/json

{
  "followerId": 2,
  "followedId": 1
}

###

### 🔹 Obtener todos los follows
GET http://localhost:4200/api/user-follows
Accept: application/json

###

### 🔹 Obtener un follow por ID
GET http://localhost:4200/api/user-follows/1
Accept: application/json

###

### 🔹 Actualizar un follow
PUT http://localhost:4200/api/user-follows/1
Content-Type: application/json

{
  "followerId": 1,
  "followedId": 3
}

###

### 🔹 Eliminar un follow
DELETE http://localhost:4200/api/user-follows/6
Accept: application/json

### Unfollow (Eliminar relación por followerId y followedId)
DELETE http://localhost:4200/api/user-follows/unfollow
Content-Type: application/json

{
  "followerId": 1,
  "followedId": 3
}
