### Follow - crear relación (POST)
POST http://localhost:4200/friendships/follow
Content-Type: application/json

{
  "followerId": 2,
  "followedId": 3
}

###

### Get followers of user 2
GET http://localhost:4200/friendship/followers/2

###

### Get following of user 1
GET http://localhost:4200/friendship/following/1

###

### Unfollow by friendship id (DELETE)
DELETE http://localhost:4200/friendship/unfollow/1
