
### Crear
POST http://localhost:4200/api/songs
Content-Type: application/json

{
  "title": "Baila askldHSAJ",
  "audioUrl": "https://www.youtube.com/watch?v=_KKN6WGebGg&list=RD_KKN6WGebGg&start_radio=1&ab_channel=NanpaBasicoVEVO",
  "genre": "Electronica",
  "duration": 192

}


###Listar
GET http://localhost:4200/api/songs


### Buscar
GET http://localhost:4200/api/songs?query=Electronic

### Actualizar 
PATCH http://localhost:4200/api/songs/3
Content-Type: application/json

{ "album": "PresenceFabian" }


### Pa borrar 
DELETE http://localhost:4200/api/songs/5
