# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - harmonysocial-api

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build
        run: |
          cd ./Backend
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'harmonysocial-api'
          slot-name: 'Production'
          package: .

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9F668B43980F4E7B9EADCE48CAA4C80B }}
          
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: seed:permissions
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
          DB_SYNC: ${{ secrets.DB_SYNC }}
          DB_PORT: ${{ secrets.DB_PORT }}
          
          # Variables de entorno adicionales requeridas por el backend
          PORT: ${{ vars.PORT }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}

          # Seguridad
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ vars.PASSWORD_SALT }}

          # SMTP
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

          # Frontend / CORS
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          ALLOWED_URLS: ${{ secrets.ALLOWED_URLS }}

          # Azure Storage
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

        run: |
          cd ./Backend
          npm install --production
          npm run seed:permissions

